### ISSUE TITLE
 Cannot read property 'names' of undefined

### ISSUE THREAD

**Issue by askie** [mishguruorg/angular-timezone-selector#39]
`angular.min.js:107 TypeError: Cannot read property 'names' of undefined
    at Object.get (http://192.168.3.11:4040/web/erp/bower_components/angular-timezone-selector/dist/angular-timezone-selector.min.js:1:196)
    at link (http://192.168.3.11:4040/web/erp/bower_components/angular-timezone-selector/dist/angular-timezone-selector.min.js:1:26857)
    at http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:73:222
    at ca (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:73:279)
    at I (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:62:174)
    at g (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:55:97)
    at g (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:55:114)
    at g (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:55:114)
    at g (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:55:114)
    at g (http://192.168.3.11:4040/web/erp/bower_components/angular/angular.min.js:55:114) <select style="min-width:300px;;min-width:300px;" ng-model="timezone" class="ng-isolate-scope">`

**Comment by ashokfernandez** [comment]
Do you have any more info on what version you're using? How it's being built? Does turning off minification fix the issue?

**Comment by ashokfernandez** [comment]
I'm going to close this since you haven't added any more information and it doesn't seem to be effecting other users, more likely a problem with your setup

**Comment by lindamarieb** [comment]
I'm also getting this error. I'm using:

AngularJS v1.3.20
moment.js 2.10.6
moment-timezone.js 0.4.1
lodash 4.0.1
